apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 5s
  path: ./apps/base
  prune: true
  timeout: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
  env:
   -name: MYSQL_USERNAME
    valueFrom: 
    secretKeyRef:
      name: basic-auth
      key: user
   -name: MYSQL_PASSWORD
    valueFrom: 
    secretKeyRef:
      name: basic-auth
      key: password   
