apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth
  namespace: default
spec:
  encryptedData:
    password: AgCAZuQVer2e68+yCaaP7E7gJhcwdqJepUT53iJIBneSbefwTFfYv8mYPhY+VuXzCNWn7/M6XI+WSjvIpllEmHfBEevBXmz+ejfAR4Pm0ifYJAwm4NgbYoQyafxqd8olWjZtfa9cEBGMRmLLM+q84uH1g9fI+GlTowkUPwBKkL3ierDELBXsStsbVXZL88OGo9/mVTq7arXkebIUjkXykCqZU7qM23per1fZdx2PNOdBdjFQRaoBbhw3kmiNPkh+Q76BgYbucLk/gmS1vVwP3OWgxms7xZ5IYXFmIGbHarGT2HKLL5KY80tXoA9bWCImsSR6bD2E8RRrNE8cYH9DXz1Lo0hQj4VBCSx22k2fbMzOvfdgNOserYZMEp3aCK+P1D2xTCrRFIuY3s5LBBgYiA2m9ce4nIhiYsPJ1hp+0VcHIIplF7VKlR+aH6yXbhWDD7r/O6YL5zfBtikCErOo/cKTBvVTm0QftxDhx54MyKb6VOVhoLuP23RWlWg5T8USVYgHlu/Ske95OAx+RmNq8S2NSVxoTk3MBwCQNa29LmT/1ZoY5bdylYobfaeeh6HCgOeQVcQWbc8nFtER69gqoYw11/JUP9VIUiNGFD0pQOusleWyHyc1h320xmwhQ9srtQge4vMEnM5Rw+tBZeEj59Ug2AjVrnzdg0aLgFDvOu+Vqd5JzO7y0ruWY/un91f7gHSifZOlclMq5eQ=
    user: AgC8Khe1lpGqsjiMNGOW30jjW6JKG7m5VgNs1P+IHSoqDQEjYRouAmD1zTtZSqnKnCkcqHLY9/uKAIbLSUb+tAXF9Ls1xuLhIDKqWmwpTpgQpDmQslc9U9de4ml8ry4/kKa0u3g9QitRxJku/Y1aicRLsi0dm6YTjBvvxtwLcoMM0C/92uKWBzhUiUJepsWbn67zAW7euLT+GSmvVEqGUDrCPKvq0dmdn5S51+dNVUZ/iNgwRqmhzTr6keQNp0xRvZVFicGauHR6z8P2np/YjZyFzmPpTvZKbcD6TS2lOxd14d0TXoaEP9+WhjbpD0IXGpDL01LxW9JBQRegQB0FDB+cjJGCwUy/UZvQjANpJ4V+aDxauUwm60xnvoGQiGrJkxYCNuleNg9MFnREjyCDSI050y9EFGLI+4JSbK/f7+tLTVhWo3b1OJRZcC8L2X/DQy5Yd3WFeWZv/zjQ2ufKHYh4HhRe7F6UTysOJrHefnvNfwGiK5wxKZDUbwT346Z8JlXcigtxV5CpJ159WV0CTvLC+6+m/vdvRYus4FMRwHGhijavBHoRYn6u+/ys/CXR8+GZ/GlGhYhuEXuZcfkT4gHU0fa1QARWziMgDg9zLkK9tLtFTRtvytT2pt9bMaXEtemN/Cpj9f/Ppx2hEFjGL5aD1QD38c4yED9iRldMaHeeFuI8RUL2OhuSUKgYDPZZPfx3NTinig==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth
      namespace: default

