apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joomla
  namespace: flux-system
spec:
  chart:
    spec:
      chart: joomla
      sourceRef:
        kind: HelmRepository
        name: bitnami

      env:
        -name: JOOMLA_CREDS
        valueFrom: 
        secretKeyRef:
          name: basic-auth
          key1: user
          key: password
      releaseName: joomla
  interval: 1m0s      
  

